### ISSUE TITLE
Publish on Flathub?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [pwmt/zathura#655]
Are there any plans to publish the app on Flathub?

**Comment by sebastinas** [comment]
Happy to take patches, but not going to work on it myself.

**Comment by yellowhat** [comment]
I am trying to create a flatpak manifest:

<details>
    <summary>org.pwmt.zathura.yaml</summary>

```yaml
---
app-id: org.pwmt.zathura

runtime: org.freedesktop.Platform
runtime-version: "24.08"
sdk: org.freedesktop.Sdk

command: zathura

finish-args:
  - --device=dri
  - --filesystem=xdg-documents
  - --filesystem=xdg-download
  - --share=ipc
  - --socket=wayland

cleanup:
  - /include
  - /lib/cmake
  - /lib/pkgconfig
  - /share/man
  - '*.la'
  - '*.a'

modules:
  - name: zathura
    buildsystem: meson
    sources:
      - type: archive
        url: https://github.com/pwmt/zathura/archive/0.5.11.tar.gz
        sha256: 32540747a6fe3c4189ec9d5de46a455862c88e11e969adb5bc0ce8f9b25b52d4
        x-checker-data:
          type: anitya
          project-id: 5298
          stable-only: true
          url-template: https://github.com/pwmt/zathura/archive/$version.tar.gz
    modules:
      - name: girara
        buildsystem: meson
        sources:
          - type: archive
            url: https://pwmt.org/projects/girara/download/girara-0.4.5.tar.xz
            sha256: 6b7f7993f82796854d5036572b879ffaaf7e0b619d12abdb318ce14757bdda91
            x-checker-data:
              type: anitya
              project-id: 6750
              stable-only: true
              url-template: https://pwmt.org/projects/girara/download/girara-$version.tar.xz

  - name: zathura-pdf-mupdf
    buildsystem: meson
    sources:
      - type: archive
        url: https://github.com/pwmt/zathura-pdf-mupdf/archive/0.4.4.tar.gz
        sha256: 90bdc7c0d4b5f6bd7b17f9c3832ae5eb8465b45d78ab3b8c2fca26ed45ed1177
        x-checker-data:
          type: anitya
          project-id: 14846
          stable-only: true
          url-template: https://github.com/pwmt/zathura-pdf-mupdf/archive/$version.tar.gz
      - type: shell
        commands:
          - sed -i '/mupdfthird/d' meson.build
    modules:
      - name: mupdf
        no-autogen: true
        build-options:
          cflags: '-fPIC'
          cxxflags: '-fPIC'
          env:
            USE_SYSTEM_LIBS: 'yes'
        make-args:
          - shared=yes
          - build=release
          - libs
        make-install-args:
          - shared=yes
          - build=release
          - libs
          - prefix=${FLATPAK_DEST}
        post-install:
          - |
            libmupdf_ver=$(grep '#define FZ_VERSION' ${FLATPAK_DEST}/include/mupdf/fitz/version.h | head -1 | cut -d\" -f2)
            sed -i 's/\$\$VERSION\$\$/'${libmupdf_ver}'/' mupdf.pc
          - install -Dm644 mupdf.pc -t ${FLATPAK_DEST}/lib/pkgconfig/
        sources:
          - type: archive
            url: https://mupdf.com/downloads/archive/mupdf-1.25.2-source.tar.gz
            sha256: 36ccf6a5e691e188acf8db6e98d08bf05f27bb4ce30432dc15fc76d329a92d4d
            x-checker-data:
              type: anitya
              project-id: 2034
              stable-only: true
              url-template: https://mupdf.com/downloads/archive/mupdf-$version-source.tar.gz
          - type: file
            path: mupdf.pc
          - type: shell
            commands:
              - rm -rf thirdparty/{freeglut,freetype,harfbuzz,jbig2dec,libjpeg,openjpeg,zlib}
        cleanup:
          - /bin
          - /share
        modules:
          - name: glu
            buildsystem: meson
            sources:
              - type: archive
                url: https://archive.mesa3d.org/glu/glu-9.0.3.tar.xz
                sha256: bd43fe12f374b1192eb15fe20e45ff456b9bc26ab57f0eee919f96ca0f8a330f
          - name: freeglut
            buildsystem: cmake-ninja
            sources:
              - type: archive
                url: https://github.com/freeglut/freeglut/releases/download/v3.6.0/freeglut-3.6.0.tar.gz
                sha256: 9c3d4d6516fbfa0280edc93c77698fb7303e443c1aaaf37d269e3288a6c3ea52
                x-checker-data:
                  type: anitya
                  project-id: 846
                  stable-only: true
                  url-template: https://github.com/freeglut/freeglut/releases/download/v$version/freeglut-$version.tar.gz
          - name: libXmu
            sources:
              - type: archive
                url: https://www.x.org/releases/individual/lib/libXmu-1.2.1.tar.gz
                sha256: bf0902583dd1123856c11e0a5085bd3c6e9886fbbd44954464975fd7d52eb599
          - name: jbig2dec
            sources:
              - type: archive
                url: https://github.com/ArtifexSoftware/jbig2dec/archive/0.20.tar.gz
                sha256: a9705369a6633aba532693450ec802c562397e1b824662de809ede92f67aff21
                x-checker-data:
                  type: anitya
                  project-id: 1431
                  stable-only: true
                  url-template: https://github.com/ArtifexSoftware/jbig2dec/archive/$version.tar.gz
          - name: gumbo-parser
            sources:
              - type: archive
                url: https://github.com/google/gumbo-parser/archive/v0.10.1.tar.gz
                sha256: 28463053d44a5dfbc4b77bcf49c8cee119338ffa636cc17fc3378421d714efad
                x-checker-data:
                  type: anitya
                  project-id: 214990
                  stable-only: true
                  url-template: https://github.com/google/gumbo-parser/archive/v$version.tar.gz
          - name: leptonica
            buildsystem: autotools
            sources:
              - type: archive
                url: https://github.com/DanBloomberg/leptonica/releases/download/1.85.0/leptonica-1.85.0.tar.gz
                sha256: 3745ae3bf271a6801a2292eead83ac926e3a9bc1bf622e9cd4dd0f3786e17205
          - name: tesseract
            buildsystem: autotools
            sources:
              - type: archive
                url: https://github.com/tesseract-ocr/tesseract/archive/5.5.0.tar.gz
                sha256: f2fb34ca035b6d087a42875a35a7a5c4155fa9979c6132365b1e5a28ebc3fc11
          - name: mujs
            no-autogen: true
            make-args:
              - release
            make-install-args:
              - prefix=${FLATPAK_DEST}
              - install-shared
            cleanup:
              - /bin
              - /include
              - /lib/pkgconfig
            sources:
              - type: archive
                url: https://github.com/ccxvii/mujs/archive/1.3.5.tar.gz
                sha256: 78a311ae4224400774cb09ef5baa2633c26971513f8b931d3224a0eb85b13e0b
```

</details>


<details>
    <summary>mupdf.pc</summary>

```
prefix=/app
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: mupdf
Description: Library for rendering PDF documents
Version: $$VERSION$$
Libs: -L${libdir} -lmupdf
Cflags: -I${includedir}
```

</details>

The flatpak is created but on opening a pdf a I get:

```
error: Could not load plugin '/app/lib/zathura/libpdf-mupdf.so' (/app/lib/zathura/libpdf-mupdf.so: undefined symbol: fz_identity).
warning: Found no plugins. Please install at least one plugin.
info: Opening plain database via sqlite backend.
info: No plain database available. Continuing with sqlite database.
error: Could not determine file type.
```

Any suggestions?

Thanks
